FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
# ARG JAR_FILE=*.jar
# COPY ${JAR_FILE} application.jar
COPY target/eshop-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "eshop-0.0.1-SNAPSHOT.jar"]
