FROM maven:3.8.2-jdk-8
WORKDIR /app
COPY . .
# RUN mvn package
CMD ["mvn", "spring-boot:run"]
# CMD ["java", "-jar", "eshop-0.0.1-SNAPSHOT.jar"]
# FROM adoptopenjdk:11-jre-hotspot
# WORKDIR /app
# # ARG JAR_FILE=*.jar
# # COPY ${JAR_FILE} application.jar
# RUN mvn clean spring-boot:run
# COPY target/eshop-0.0.1-SNAPSHOT.jar .
# EXPOSE 8080
# CMD ["java", "-jar", "eshop-0.0.1-SNAPSHOT.jar"]
